In [643]:
import numpy as np
import matplotlib.pyplot as plt
import random

# Задание 1

Решить линейную регрессию — найти прямую, которая описывает зависимость

N - количество осей (размерность) <br>
M - количество точек <br>
minValue - минимальное значение для иксов <br>
maxValue - максимальное значение для иксов

In [644]:
N = 3
M = 10
minValue = 0
maxValue = 10
EPS = 1e-6
K = 1e-2


In [645]:
def yRegression(B, X):
    return np.sum(X * B)

B_reg = []
for i in range(N + 1):
    bi = random.randint(minValue, maxValue)
    B_reg.append(bi)
B_reg = np.array(B_reg, dtype='float64')
print(B_reg)
XM = []
YM = []
YR = []
for i in range(M):
    X = [1]
    for j in range(N):
        xj = random.randint(minValue, maxValue)
        X.append(xj)
    X = np.array(X)
    rand_delta = random.randint(-maxValue, maxValue)
    Y_r = yRegression(B_reg, X)
    Y_act = Y_r + random.randint(0, 10) * rand_delta
    YM.append(Y_act)
    XM.append(np.array(X))
    YR.append(Y_r)
XM = np.array(XM, dtype='float64')
YM = np.array(YM)
YR = np.array(YR)
print(XM)
print(YM)
print(YR)

[2. 0. 4. 8.]
[[ 1.  1.  8.  3.]
 [ 1.  4.  3.  1.]
 [ 1.  7.  4.  7.]
 [ 1.  7.  7.  8.]
 [ 1.  6.  9.  1.]
 [ 1.  6.  4.  2.]
 [ 1.  1.  0.  2.]
 [ 1.  9.  5.  4.]
 [ 1. 10.  8.  8.]
 [ 1.  9.  3. 10.]]
[ 58. -41. 114. 144.  52.  16. -62.  60.  83. 115.]
[58. 22. 74. 94. 46. 34. 18. 54. 98. 94.]


In [646]:
def squaredError(Y_act, Y_reg):
    error = 0
    for i in range(M):
        error += (Y_act[i] - Y_reg[i]) ** 2
    return error

def stoppingCriteria(previous, current):
    return abs(previous - current) < EPS

def gradient(nums, XM, YR, YM):
    grad = []
    for i in range(N + 1):
        xi = 0
        for j in range(len(nums)):
            xi += XM[nums[j]][i] * (YR[nums[j]] - YM[nums[j]])
        xi *= 2
        grad.append(xi)
    return np.array(grad)

def gradientDescent(batch, XM, YM, YR, B_reg):
    previous = 0
    errors = []
    while True:
        nums = set()
        while len(nums) != batch:
            x = random.randint(0, M - 1)
            if x not in nums:
                nums.add(x)

        nums = np.array(list(nums))
        grad = gradient(nums, XM, YR, YM)
        B_reg -= K * grad
        for i in range(M):
            YR[i] = yRegression(B_reg, XM[i])
        if stoppingCriteria(previous, squaredError(YM, YR)):
            break
        previous = squaredError(YM, YR)
        errors.append(previous)
    return B_reg, errors, YR

def drawGraph(XM, YM, YF):
    fig = plt.figure()
    fig.set_size_inches(10, 10)
    X = XM.T[1]
    plt.scatter(X, YM)
    plt.plot(X, YF)
    plt.show()

B_final, errors, YF = gradientDescent(1, XM, YM, YR, B_reg)

print(errors[0], errors[len(errors) - 1])
drawGraph(XM, YM, YF)

/var/folders/jf/t98pfdyj3496cy7sfv395_j80000gn/T/ipykernel_3942/3306241826.py:4: RuntimeWarning: overflow encountered in double_scalars
  error += (Y_act[i] - Y_reg[i]) ** 2
/var/folders/jf/t98pfdyj3496cy7sfv395_j80000gn/T/ipykernel_3942/3306241826.py:8: RuntimeWarning: invalid value encountered in double_scalars
  return abs(previous - current) < EPS
/var/folders/jf/t98pfdyj3496cy7sfv395_j80000gn/T/ipykernel_3942/3306241826.py:16: RuntimeWarning: overflow encountered in double_scalars
  xi *= 2
/var/folders/jf/t98pfdyj3496cy7sfv395_j80000gn/T/ipykernel_3942/3306241826.py:32: RuntimeWarning: invalid value encountered in subtract
  B_reg -= K * grad
/var/folders/jf/t98pfdyj3496cy7sfv395_j80000gn/T/ipykernel_3942/1446548817.py:2: RuntimeWarning: invalid value encountered in multiply
  return np.sum(X * B)


KeyboardInterrupt: 

# Задание 2

In [ ]:
def ZNormalization(XM):
    X = XM.T
    for i in range(1, N + 1):
        X[i] = (X[i] - np.mean(X[i])) / np.std(X[i])
    return X.T

# print(XM)
X_norm = ZNormalization(XM)
Y_norm = (YM - np.mean(YM)) / np.std(YM)
B_norm = (B_reg - np.mean(B_reg)) / np.std(B_reg)
BF_norm, errors_norm, YF_norm = gradientDescent(1, X_norm, Y_norm, YR, B_norm)

print(errors_norm[0], errors_norm[len(errors_norm) - 1])
drawGraph(X_norm, Y_norm, YF_norm)